import { useState, useEffect, useMemo } from 'react';
import PropTypes from 'prop-types';
import { DisplayGraph } from './Utils/DisplayGraph';

/**
 * Component for visualizing the step-by-step winning strategy analysis for a combinatorial game.
 * Uses the iterative steps generated by computeWinner.
 * 
 * @component
 * @param {Object} props - The component props
 * @param {Object} props.graph - The game graph to analyze
 */
export function StepByStepGame({ graph, analysisSteps }) {
  const [steps, setSteps] = useState([]);
  const [currentStep, setCurrentStep] = useState(0);

  // Load steps from the pre-computed analysisSteps prop
  useEffect(() => {
    if (graph && analysisSteps) {
      const allSteps = [
        {
          type: 'INIT',
          explanation: 'Začátek analýzy. Všechny pozice jsou zatím nezpracované. Nejprve identifikujeme koncové pozice bez tahů.',
          accumulatedStatus: {}
        },
        ...analysisSteps
      ];
      setSteps(allSteps);
      setCurrentStep(0);
    }
  }, [graph, analysisSteps]);

  // Navigation functions
  const goToNextStep = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1);
    }
  };

  const goToPreviousStep = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const goToFirstStep = () => {
    setCurrentStep(0);
  };

  const goToLastStep = () => {
    setCurrentStep(steps.length - 1);
  };

  // Construct the accumulated winning map for the current step
  // We can't rely on the step object having the full map unless we build it here.
  // The steps from computeWinner are incremental updates.
  // So we need to compute the state at `currentStep`.
  
  const currentStatusMap = useMemo(() => {
    const map = {};
    // Replay steps up to currentStep
    for (let i = 1; i <= currentStep; i++) { // Skip INIT step 0
      const step = steps[i];
      if (step && step.id && step.type !== 'FINAL') {
         // Determine winning player based on status relative to node owner
         // step.status is 'WIN' or 'LOSE' for the player at step.id
         const position = graph.positions[step.id];
         if (!position) continue;
         const nodePlayer = position.player;
         let winner = 0;
         if (step.status === 'WIN') {
             winner = nodePlayer;
         } else if (step.status === 'LOSE') {
             winner = nodePlayer === 1 ? 2 : 1;
         }
         
         if (winner !== 0) {
             map[step.id] = winner;
         }
      }
    }
    return map;
  }, [currentStep, steps, graph]);

  // Determine optimal moves for visualization
  // Optimal moves are edges from P1-Winning node to P1-Winning node.
  // We use currentStatusMap where 1 = P1 Win, 2 = P2 Win (P1 Lose).
  const currentOptimalMoves = useMemo(() => {
      const moves = new Set();
      for (const posId in graph.positions) {
          // If this position is determined as P1 Winning (map value 1) AND it's P1's turn
          // (Wait, optimal moves logic in DisplayGraph usually just highlights P1 winning paths)
          // Let's stick to: From P1-Win to P1-Win.
          
          if (currentStatusMap[posId] === 1 && graph.positions[posId].player === 1) {
               const children = graph.positions[posId].children || [];
               children.forEach(childId => {
                   if (currentStatusMap[childId] === 1) {
                       moves.add(`${posId}-${childId}`);
                   }
               });
          }
      }
      return moves;
  }, [currentStatusMap, graph]);

  const activeStep = steps[currentStep];

  return (
    <div className="step-by-step-container d-flex flex-column" style={{ height: '100%', overflow: 'hidden' }}>
      <h2 className="text-center mb-3" style={{ flexShrink: 0 }}>Postupná analýza výherní strategie</h2> 
      {steps.length > 0 ? (
        <>
          <div className="flex-grow-1 d-flex flex-column" style={{ minHeight: 0, overflow: 'auto' }}>
            <DisplayGraph 
              graph={graph} 
              optimalMoves={currentOptimalMoves}
              highlightedNode={activeStep?.id}
              winningPlayerMap={currentStatusMap}
              trackHighlightedNode={true}
              showLockControl={true}
            />
          </div>
          
          <div className='step-controls-info container-fluid mt-3' style={{ flexShrink: 0 }}>
          <div className='row align-items-center'>
            <div className='step-info col-md-7'>
              <div className={`card p-3 ${activeStep?.type === 'FINAL' ? '' : 'bg-light'}`} style={{ minHeight: '140px', backgroundColor: activeStep?.type === 'FINAL' ? 'rgba(255, 255, 0, 0.2)' : undefined }}>
                <p className="mb-1"><strong>Typ:</strong> {activeStep?.type === 'INIT' ? 'Inicializace' : (activeStep?.type === 'TERMINAL' ? 'Koncová pozice' : (activeStep?.type === 'FINAL' ? 'Výsledek analýzy' : 'Propagace výsledku'))}</p>
                
                {activeStep?.id && activeStep?.type !== 'FINAL' && (
                    <p className="mb-1">
                        <strong>Pozice:</strong> {activeStep.id} (Hráč {graph.positions[activeStep.id]?.player})
                    </p>
                )}
                
                {activeStep?.type === 'FINAL' && (
                    <p className="mb-1">
                        <strong>Počáteční pozice:</strong> {activeStep.id} (Hráč {graph.positions[activeStep.id]?.player})
                    </p>
                )}
                
                <p className="mb-1"><strong>Vysvětlení:</strong> {activeStep?.explanation}</p>
                
                {activeStep?.status && activeStep?.type !== 'FINAL' && (
                    <p className="mb-0">
                    <strong>Stav:</strong>{' '}
                    <span className={
                        (activeStep.status === 'WIN' && graph.positions[activeStep.id].player === 1) || 
                        (activeStep.status === 'LOSE' && graph.positions[activeStep.id].player === 2) 
                        ? 'text-success fw-bold' : 'text-danger fw-bold'
                    }>
                        {((activeStep.status === 'WIN' && graph.positions[activeStep.id].player === 1) || 
                          (activeStep.status === 'LOSE' && graph.positions[activeStep.id].player === 2))
                          ? 'Hráč 1 vyhrává' : 'Hráč 1 prohrává'}
                    </span>
                    </p>
                )}

                {activeStep?.type === 'FINAL' && (
                    <p className="mb-0">
                    <strong>Výsledek:</strong>{' '}
                    <span className="fw-bold">
                        {activeStep.hasWinningStrategy ? 'Hráč 1 má výherní strategii' : 'Hráč 1 nemá výherní strategii'}
                    </span>
                    </p>
                )}
              </div>
            </div>
            <div className='step-controls col-md-5 d-flex flex-column align-items-center justify-content-center'>
              <p className="text-center mb-2">Krok {currentStep} z {steps.length - 1}</p>
              <div className="step-button-group d-flex gap-2">
                <button className='btn btn-secondary btn-sm' onClick={goToFirstStep} disabled={currentStep === 0} aria-label="Přeskočit na začátek">
                  <i className="bi bi-skip-start-fill"></i>
                </button>
                <button className='btn btn-secondary' onClick={goToPreviousStep} disabled={currentStep === 0} aria-label="Předchozí krok">
                  <i className="bi bi-chevron-left"></i> Předchozí
                </button>
                <button className='btn btn-primary' onClick={goToNextStep} disabled={currentStep === steps.length - 1} aria-label="Další krok">
                  Další <i className="bi bi-chevron-right"></i>
                </button>
                <button className='btn btn-primary btn-sm' onClick={goToLastStep} disabled={currentStep === steps.length - 1} aria-label="Přeskočit na konec">
                  <i className="bi bi-skip-end-fill"></i>
                </button>
              </div>
            </div>
          </div>
          </div>
        </>
      ) : (
        <div className="alert alert-info text-center">
            Načítání analýzy...
        </div>
      )}
    </div>
  );  
}

StepByStepGame.propTypes = {
  graph: PropTypes.shape({
    positions: PropTypes.object.isRequired,
    startingPosition: PropTypes.object.isRequired
  }).isRequired,
  analysisSteps: PropTypes.array.isRequired
};