import { useState, useMemo, useEffect } from 'react';
import PropTypes from 'prop-types';
import { DisplayGraph } from './Utils/DisplayGraph';

const resolvePlayerOneWinningAtStep = (step, graph) => {
  if (!step?.status || step?.type === 'FINAL' || !step?.id) {
    return null;
  }

  const nodePlayer = graph.positions[step.id]?.player;
  if (nodePlayer === undefined) {
    return null;
  }

  return (
    (step.status === 'WIN' && nodePlayer === 1) || (step.status === 'LOSE' && nodePlayer === 2)
  );
};

/**
 * Component for visualizing the step-by-step winning strategy analysis for a combinatorial game.
 * Uses the iterative steps generated by computeWinner.
 *
 * @component
 * @param {Object} props - The component props
 * @param {Object} props.graph - The game graph to analyze
 */
export function StepByStepGame({ graph, analysisSteps }) {
  const [currentStep, setCurrentStep] = useState(0);
  const [fitTrigger, setFitTrigger] = useState(0);

  const steps = useMemo(() => {
    if (!graph || !analysisSteps) {
      return [];
    }

    return [
      {
        type: 'INIT',
        explanation:
          'Začátek analýzy. Všechny pozice jsou zatím nezpracované. Nejprve identifikujeme koncové pozice bez tahů.',
        accumulatedStatus: {},
      },
      ...analysisSteps,
    ];
  }, [graph, analysisSteps]);

  // Reset navigation when a new analysis is loaded.
  useEffect(() => {
    if (steps.length > 0) {
      setCurrentStep(0);
      setFitTrigger((prev) => prev + 1);
    }
  }, [steps]);

  // Keep step index valid when steps change.
  useEffect(() => {
    if (steps.length === 0) {
      if (currentStep !== 0) {
        setCurrentStep(0);
      }
      return;
    }

    if (currentStep > steps.length - 1) {
      setCurrentStep(steps.length - 1);
    }
  }, [steps.length, currentStep]);

  // Navigation functions
  const goToNextStep = () => {
    setCurrentStep((prev) => Math.min(prev + 1, Math.max(steps.length - 1, 0)));
  };

  const goToPreviousStep = () => {
    setCurrentStep((prev) => Math.max(prev - 1, 0));
  };

  const goToFirstStep = () => {
    setCurrentStep(0);
  };

  const goToLastStep = () => {
    if (steps.length > 0) {
      setCurrentStep(steps.length - 1);
    }
  };

  // Rebuild status map up to current step.

  const currentStatusMap = useMemo(() => {
    const map = {};
    // Replay incremental updates.
    for (let i = 1; i <= currentStep; i++) {
      // Skip INIT step.
      const step = steps[i];
      if (step && step.id && step.type !== 'FINAL') {
        // Resolve winner from node owner and step status.
        const position = graph.positions[step.id];
        if (!position) continue;
        const nodePlayer = position.player;
        let winner = 0;
        if (step.status === 'WIN') {
          winner = nodePlayer;
        } else if (step.status === 'LOSE') {
          winner = nodePlayer === 1 ? 2 : 1;
        }

        if (winner !== 0) {
          map[step.id] = winner;
        }
      }
    }
    return map;
  }, [currentStep, steps, graph]);

  // Highlight P1-to-P1 winning moves.
  const currentOptimalMoves = useMemo(() => {
    const moves = new Set();
    for (const posId in graph.positions) {
      // Use positions where Player 1 is winning and moves next.

      if (currentStatusMap[posId] === 1 && graph.positions[posId].player === 1) {
        const children = graph.positions[posId].children || [];
        children.forEach((childId) => {
          if (currentStatusMap[childId] === 1) {
            moves.add(`${posId}-${childId}`);
          }
        });
      }
    }
    return moves;
  }, [currentStatusMap, graph]);

  const activeStep = steps[currentStep];
  const isPlayerOneWinningAtActiveStep = useMemo(
    () => resolvePlayerOneWinningAtStep(activeStep, graph),
    [activeStep, graph]
  );

  // Ensure final conclusion step shows the whole graph, not just the highlighted node.
  useEffect(() => {
    if (activeStep?.type === 'FINAL') {
      setFitTrigger((prev) => prev + 1);
    }
  }, [activeStep]);

  return (
    <div
      className="step-by-step-container d-flex flex-column"
      style={{ height: '100%', overflow: 'hidden' }}
    >
      <h2 className="text-center mb-3" style={{ flexShrink: 0 }}>
        Postupná analýza výherní strategie
      </h2>
      {steps.length > 0 ? (
        <>
          <div
            className="flex-grow-1 d-flex flex-column"
            style={{ minHeight: 0, overflow: 'auto' }}
          >
            <DisplayGraph
              graph={graph}
              optimalMoves={currentOptimalMoves}
              highlightedNode={activeStep?.id}
              winningPlayerMap={currentStatusMap}
              trackHighlightedNode={activeStep?.type !== 'FINAL'}
              fitTrigger={fitTrigger}
              showLockControl={true}
              defaultLocked={true}
              lockOnFirstTick={true}
            />
          </div>

          <div className="step-controls-info container-fluid mt-3" style={{ flexShrink: 0 }}>
            <div className="row align-items-center">
              <div className="step-info col-md-7">
                <div
                  className={`card p-3 ${activeStep?.type === 'FINAL' ? '' : 'bg-light'}`}
                  style={{
                    minHeight: '140px',
                    backgroundColor:
                      activeStep?.type === 'FINAL' ? 'rgba(255, 255, 0, 0.2)' : undefined,
                  }}
                >
                  <p className="mb-1">
                    <strong>Typ:</strong>{' '}
                    {activeStep?.type === 'INIT'
                      ? 'Inicializace'
                      : activeStep?.type === 'TERMINAL'
                        ? 'Koncová pozice'
                        : activeStep?.type === 'FINAL'
                          ? 'Výsledek analýzy'
                          : 'Propagace výsledku'}
                  </p>

                  {activeStep?.id && activeStep?.type !== 'FINAL' && (
                    <p className="mb-1">
                      <strong>Pozice:</strong> {activeStep.id} (Hráč{' '}
                      {graph.positions[activeStep.id]?.player})
                    </p>
                  )}

                  {activeStep?.type === 'FINAL' && (
                    <p className="mb-1">
                      <strong>Počáteční pozice:</strong> {activeStep.id} (Hráč{' '}
                      {graph.positions[activeStep.id]?.player})
                    </p>
                  )}

                  <p className="mb-1">
                    <strong>Vysvětlení:</strong> {activeStep?.explanation}
                  </p>

                  {activeStep?.status && activeStep?.type !== 'FINAL' && (
                    <p className="mb-0">
                      <strong>Stav:</strong>{' '}
                      <span
                        className={
                          isPlayerOneWinningAtActiveStep
                            ? 'text-success fw-bold'
                            : 'text-danger fw-bold'
                        }
                      >
                        {isPlayerOneWinningAtActiveStep ? 'Hráč 1 vyhrává' : 'Hráč 1 prohrává'}
                      </span>
                    </p>
                  )}

                  {activeStep?.type === 'FINAL' && (
                    <p className="mb-0">
                      <strong>Výsledek:</strong>{' '}
                      <span className="fw-bold">
                        {activeStep.hasWinningStrategy
                          ? 'Hráč 1 má výherní strategii'
                          : 'Hráč 1 nemá výherní strategii'}
                      </span>
                    </p>
                  )}
                </div>
              </div>
              <div className="step-controls col-md-5 d-flex flex-column align-items-center justify-content-center">
                <p className="text-center mb-2">
                  Krok {currentStep} z {steps.length - 1}
                </p>
                <div className="step-button-group d-flex gap-2">
                  <button
                    type="button"
                    className="btn btn-secondary btn-sm"
                    onClick={goToFirstStep}
                    disabled={currentStep === 0}
                    aria-label="Přeskočit na začátek"
                  >
                    <i className="bi bi-skip-start-fill"></i>
                  </button>
                  <button
                    type="button"
                    className="btn btn-secondary"
                    onClick={goToPreviousStep}
                    disabled={currentStep === 0}
                    aria-label="Předchozí krok"
                  >
                    <i className="bi bi-chevron-left"></i> Předchozí
                  </button>
                  <button
                    type="button"
                    className="btn btn-primary"
                    onClick={goToNextStep}
                    disabled={currentStep === steps.length - 1}
                    aria-label="Další krok"
                  >
                    Další <i className="bi bi-chevron-right"></i>
                  </button>
                  <button
                    type="button"
                    className="btn btn-primary btn-sm"
                    onClick={goToLastStep}
                    disabled={currentStep === steps.length - 1}
                    aria-label="Přeskočit na konec"
                  >
                    <i className="bi bi-skip-end-fill"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : (
        <div className="alert alert-info text-center">Načítání analýzy...</div>
      )}
    </div>
  );
}

StepByStepGame.propTypes = {
  graph: PropTypes.shape({
    positions: PropTypes.object.isRequired,
    startingPosition: PropTypes.object.isRequired,
  }).isRequired,
  analysisSteps: PropTypes.array.isRequired,
};
